# Generated by Django 3.2.6 on 2021-08-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marca del dispositivo')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del dispositivo')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad de dispositivos actuales')),
                ('actividad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Actividad de mantenimiento a realizar')),
                ('plan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de poliza/plan')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo Mantenimiento')),
                ('periodisidadactividades', models.IntegerField(blank=True, null=True, verbose_name='Periodicidad regular de actividad de mtto por año')),
                ('periodisidadadicional', models.IntegerField(blank=True, null=True, verbose_name='Periodicidad adicional de actividad de mtto  a la regular')),
                ('tiempoejecucion', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de ejecucion del mtto')),
                ('cantidaddispositivos', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad regular')),
                ('horasactividad', models.IntegerField(blank=True, null=True, verbose_name='horas por actividad de mtto regular =Importe de cantidad x Tiempo de ejecucion')),
                ('costomantenimientoadicional', models.IntegerField(blank=True, null=True, verbose_name='horas por actividad de mtto adicional =Importe de cantidad x Tiempo de ejecucion ')),
                ('costomantenimientoregular', models.IntegerField(blank=True, null=True, verbose_name='horas por actividad de mtto regular =Importe de cantidad x Tiempo de ejecucion')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la compañia cliente')),
                ('encargado', models.CharField(max_length=120, verbose_name='Nombre del contacto dentro de la empresa')),
                ('puesto_encargado', models.CharField(max_length=120, verbose_name='Puesto del contacto')),
                ('numero_contacto', models.CharField(max_length=10, verbose_name='Numero de telefono para contactar')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo para contactar')),
                ('lugar_de_mantenimiento', models.CharField(max_length=120, verbose_name='Lugar en que se realizara el mantenimiento')),
                ('descripcion_cotizacion', models.TextField(blank=True, verbose_name='Descripcion de la cotizacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de realizacion de la cotizacion')),
                ('dispositivo', models.ManyToManyField(blank=True, related_name='cliente', to='RPA.Dispositivo')),
                ('mantenimiento', models.ManyToManyField(blank=True, related_name='cliente', to='RPA.Mantenimiento')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
