# Generated by Django 3.2.6 on 2021-08-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de realizacion de la cotizacion'),
        ),
    ]
