# Generated by Django 3.2.6 on 2021-08-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0005_alter_cliente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de realizacion de la cotizacion'),
        ),
    ]
