# Generated by Django 3.2.6 on 2021-08-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0009_auto_20210825_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='costomantenimientoadicional',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo Adicional = horas por actividad de mtto adicional =Importe de cantidad x Tiempo de ejecucion '),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='costomantenimientoregular',
            field=models.FloatField(null=True, verbose_name='Costo Regular = horas por actividad de mtto regular =Importe de cantidad x Tiempo de ejecucion'),
        ),
    ]
