# Generated by Django 3.2.5 on 2021-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0014_auto_20210826_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['Titulo']},
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='title',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='Titulo',
            field=models.CharField(blank=True, choices=[('Revision y limpieza de panel de alarmas / Remoto', 'Revision y limpieza de panel de alarmas / Remoto'), ('Revision y limpieza de sensores de humo', 'Revision y limpieza de sensores de humo'), (' Revision y limpieza de estrobos -cornetas - campanas-mixtos', 'Revision y limpieza de estrobos -cornetas - campanas-mixtos'), ('Revision y limpieza de Fuentes de poder', 'Revision y limpieza de Fuentes de poder'), ('Revision y limpieza Palancas  de activacion', 'Revision y limpieza Palancas  de activacion'), ('Revision y limpieza Modulos monitores de Flujo', 'Revision y limpieza Modulos monitores de Flujo'), ('Revision y limpieza sensores de ductos de aire', 'Revision y limpieza sensores de ductos de aire'), ('Revision y limpieza Sensor de humo tipo Beam', 'Revision y limpieza Sensor de humo tipo Beam'), ('Revision y limpieza de modulos de Control', 'Revision y limpieza de modulos de Control'), ('Revision y limpieza de modulo de control CT1 o CT2', 'Revision y limpieza de modulo de control CT1 o CT2')], max_length=200),
        ),
    ]
