# Generated by Django 3.2.5 on 2021-09-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0016_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='encargadoTrabajo',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='encargadoTrabajo1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RPA.precio', verbose_name='Encargado del trabajo'),
        ),
    ]
