# Generated by Django 3.2.8 on 2021-10-25 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0022_auto_20210910_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 25, 0, 0), null=True, verbose_name='Fecha de realizacion de la cotizacion'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='encargadoTrabajo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RPA.precio', verbose_name='Encargado del trabajo'),
        ),
    ]
