# Generated by Django 3.2.8 on 2021-10-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0024_auto_20211026_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='marca',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dispositivos',
            field=models.ManyToManyField(blank=True, to='RPA.Dispositivo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='Titulo',
            field=models.CharField(blank=True, choices=[], max_length=200),
        ),
    ]
