# Generated by Django 3.2.8 on 2021-10-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0025_auto_20211026_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='Titulo',
            field=models.CharField(blank=True, choices=[(1, 'Revision y limpieza de panel de alarmas / Remoto'), (2, 'Revisión y limpieza de sensores de humo'), (3, 'Revisión y limpieza de estrobos -cornetas - campanas-mixtos'), (4, 'Revisión y limpieza de Fuentes de poder'), (5, 'Revisión y limpieza Palancas  de activación'), (6, 'Revisión y limpieza Módulos monitores de Flujo'), (7, 'Revisión y limpieza sensores de ductos de aire'), (8, 'Revisión y limpieza Sensor de humo tipo Beam'), (9, 'Revisión y limpieza de módulos de Control'), (10, 'Revisión y limpieza de modulo de control CT1 o CT2'), (11, 'Revisión y limpieza de modulo relevador CR'), (12, 'Revisión y Verificación de resistencias de fin de línea'), (13, 'Cambiar ubicaciones Herramientas y personal (mover el punto A al punto B)'), (14, 'Relleno de informe'), (15, 'Prueba de comunicación de datos entre panel y dispositivos, así como los loops.'), (16, 'Servicio de soporte técnico -Horas de servicios generales adicionales')], max_length=200),
        ),
    ]
