# Generated by Django 3.2.8 on 2021-10-27 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0026_alter_mantenimiento_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 27, 0, 0), null=True, verbose_name='Fecha de realizacion de la cotizacion'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='Titulo',
            field=models.CharField(blank=True, choices=[('Revision y limpieza de panel de alarmas / Remoto', 'Revision y limpieza de panel de alarmas / Remoto'), ('Revisión y limpieza de sensores de humo', 'Revisión y limpieza de sensores de humo'), ('Revisión y limpieza de estrobos -cornetas - campanas-mixtos', 'Revisión y limpieza de estrobos -cornetas - campanas-mixtos'), ('Revisión y limpieza de Fuentes de poder', 'Revisión y limpieza de Fuentes de poder'), ('Revisión y limpieza Palancas  de activación', 'Revisión y limpieza Palancas  de activación'), ('Revisión y limpieza Módulos monitores de Flujo', 'Revisión y limpieza Módulos monitores de Flujo'), ('Revisión y limpieza sensores de ductos de aire', 'Revisión y limpieza sensores de ductos de aire'), ('Revisión y limpieza Sensor de humo tipo Beam', 'Revisión y limpieza Sensor de humo tipo Beam'), ('Revisión y limpieza de módulos de Control', 'Revisión y limpieza de módulos de Control'), ('Revisión y limpieza de modulo de control CT1 o CT2', 'Revisión y limpieza de modulo de control CT1 o CT2'), ('Revisión y limpieza de modulo relevador CR', 'Revisión y limpieza de modulo relevador CR'), ('Revisión y Verificación de resistencias de fin de línea', 'Revisión y Verificación de resistencias de fin de línea'), ('Cambiar ubicaciones Herramientas y personal (mover el punto A al punto B)', 'Cambiar ubicaciones Herramientas y personal (mover el punto A al punto B)'), ('Relleno de informe', 'Relleno de informe'), ('Prueba de comunicación de datos entre panel y dispositivos, así como los loops.', 'Prueba de comunicación de datos entre panel y dispositivos, así como los loops.'), ('Servicio de soporte técnico -Horas de servicios generales adicionales', 'Servicio de soporte técnico -Horas de servicios generales adicionales')], max_length=200),
        ),
    ]
