# Generated by Django 3.2 on 2021-10-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0027_auto_20211027_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='cantidaddispositivosextras',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad regular'),
        ),
        migrations.AddField(
            model_name='nombre_servicio',
            name='cantidaddedispositivos',
            field=models.FloatField(null=True, verbose_name='Cantidad de Dispositivos'),
        ),
        migrations.AddField(
            model_name='nombre_servicio',
            name='cantidaddedispositivosextra',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad de Dispositivos Extra'),
        ),
        migrations.AddField(
            model_name='nombre_servicio',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.precio'),
        ),
        migrations.AddField(
            model_name='nombre_servicio',
            name='tiempodeejecucion',
            field=models.FloatField(null=True, verbose_name='Tiempo de Ejecucion'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='Titulo',
            field=models.CharField(blank=True, choices=[], max_length=200),
        ),
    ]
