# Generated by Django 3.2 on 2021-10-29 21:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0028_auto_20211027_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='Titulo',
            field=models.CharField(blank=True, choices=[('Revision y limpieza de panel de alarmas / Remoto', 'Revision y limpieza de panel de alarmas / Remoto'), ('Revisión y limpieza de sensores de humo', 'Revisión y limpieza de sensores de humo'), ('Revisión y limpieza de estrobos -cornetas - campanas-mixtos', 'Revisión y limpieza de estrobos -cornetas - campanas-mixtos'), ('Revisión y limpieza de Fuentes de poder', 'Revisión y limpieza de Fuentes de poder'), ('Revisión y limpieza Palancas  de activación', 'Revisión y limpieza Palancas  de activación'), ('Revisión y limpieza Módulos monitores de Flujo', 'Revisión y limpieza Módulos monitores de Flujo'), ('Revisión y limpieza sensores de ductos de aire', 'Revisión y limpieza sensores de ductos de aire'), ('Revisión y limpieza Sensor de humo tipo Beam', 'Revisión y limpieza Sensor de humo tipo Beam'), ('Revisión y limpieza de módulos de Control', 'Revisión y limpieza de módulos de Control'), ('Revisión y limpieza de modulo de control CT1 o CT2', 'Revisión y limpieza de modulo de control CT1 o CT2'), ('Revisión y limpieza de modulo relevador CR', 'Revisión y limpieza de modulo relevador CR'), ('Revisión y Verificación de resistencias de fin de línea', 'Revisión y Verificación de resistencias de fin de línea'), ('Cambiar ubicaciones Herramientas y personal (mover el punto A al punto B)', 'Cambiar ubicaciones Herramientas y personal (mover el punto A al punto B)'), ('Relleno de informe', 'Relleno de informe'), ('Prueba de comunicación de datos entre panel y dispositivos, así como los loops.', 'Prueba de comunicación de datos entre panel y dispositivos, así como los loops.'), ('Servicio de soporte técnico -Horas de servicios generales adicionales', 'Servicio de soporte técnico -Horas de servicios generales adicionales')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cantidaddispositivosextras',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad Extra'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='periodisidadadicional',
            field=models.FloatField(blank=True, null=True, verbose_name='Periodicidad adicional de actividad de mtto  a la regular'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tiempoejecucion',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo de ejecucion del mtto'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio por hora'),
        ),
    ]
