# Generated by Django 3.2.8 on 2021-11-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0029_auto_20211029_1450'),
        ('RPA', '0029_auto_20211101_0938'),
    ]

    operations = [
    ]
