# Generated by Django 3.2.8 on 2021-11-01 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0030_merge_0029_auto_20211029_1450_0029_auto_20211101_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='cantidaddispositivos',
            new_name='cantidaddedispositivos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='nombre_servicio',
            name='cantidaddedispositivos',
        ),
        migrations.RemoveField(
            model_name='nombre_servicio',
            name='cantidaddedispositivosextra',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.cliente'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='Titulo',
            field=models.CharField(blank=True, choices=[('Cambiar ubicaciones Herramientas y personal (mover el punto A al punto B)', 'Cambiar ubicaciones Herramientas y personal (mover el punto A al punto B)'), ('Prueba de comunicación de datos entre panel y dispositivos, así como los loops.', 'Prueba de comunicación de datos entre panel y dispositivos, así como los loops.'), ('Relleno de informe', 'Relleno de informe'), ('Revision y limpieza de panel de alarmas / Remoto', 'Revision y limpieza de panel de alarmas / Remoto'), ('Revisión y Verificación de resistencias de fin de línea', 'Revisión y Verificación de resistencias de fin de línea'), ('Revisión y limpieza Módulos monitores de Flujo', 'Revisión y limpieza Módulos monitores de Flujo'), ('Revisión y limpieza Palancas  de activación', 'Revisión y limpieza Palancas  de activación'), ('Revisión y limpieza Sensor de humo tipo Beam', 'Revisión y limpieza Sensor de humo tipo Beam'), ('Revisión y limpieza de Fuentes de poder', 'Revisión y limpieza de Fuentes de poder'), ('Revisión y limpieza de estrobos -cornetas - campanas-mixtos', 'Revisión y limpieza de estrobos -cornetas - campanas-mixtos'), ('Revisión y limpieza de modulo de control CT1 o CT2', 'Revisión y limpieza de modulo de control CT1 o CT2'), ('Revisión y limpieza de modulo relevador CR', 'Revisión y limpieza de modulo relevador CR'), ('Revisión y limpieza de módulos de Control', 'Revisión y limpieza de módulos de Control'), ('Revisión y limpieza de sensores de humo', 'Revisión y limpieza de sensores de humo'), ('Revisión y limpieza sensores de ductos de aire', 'Revisión y limpieza sensores de ductos de aire'), ('Servicio de soporte técnico -Horas de servicios generales adicionales', 'Servicio de soporte técnico -Horas de servicios generales adicionales')], max_length=200),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Cotizacion')),
                ('lugar_de_mantenimiento', models.CharField(blank=True, max_length=120, verbose_name='Lugar en que se realizara el mantenimiento')),
                ('descripcion_cotizacion', models.TextField(blank=True, verbose_name='Descripcion de la cotizacion')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 1, 0, 0), null=True, verbose_name='Fecha de realizacion de la cotizacion')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.cliente')),
                ('dispositivos', models.ManyToManyField(blank=True, to='RPA.Dispositivo')),
            ],
            options={
                'ordering': ['cliente'],
            },
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.cotizacion'),
        ),
        migrations.DeleteModel(
            name='cotizacion_servicio',
        ),
    ]
