# Generated by Django 3.2.8 on 2021-11-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0032_cotizacion_mantenimientos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='Mantenimientos',
            new_name='mantenimientos',
        ),
    ]
