# Generated by Django 3.2.8 on 2021-11-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0032_alter_cotizacion_mantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='nombre_servicio',
            name='cantidaddedispositivos',
        ),
        migrations.RemoveField(
            model_name='nombre_servicio',
            name='cantidaddedispositivosextra',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='Mantenimiento',
            field=models.ManyToManyField(through='RPA.Mantenimiento', to='RPA.nombre_servicio'),
        ),
    ]
