# Generated by Django 3.2 on 2021-11-02 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0033_rename_mantenimientos_cotizacion_mantenimientos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['titulonombre']},
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='encargadoTrabajo1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.precio', verbose_name='Encargado del trabajo'),
        ),
    ]
