# Generated by Django 3.2 on 2021-11-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0034_auto_20211101_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='Titulo',
        ),
    ]
