# Generated by Django 3.2.8 on 2021-11-03 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0035_remove_mantenimiento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='mmtos',
            field=models.ManyToManyField(related_name='mantenimientosCotizacion', to='RPA.Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 3, 0, 0), null=True, verbose_name='Fecha de realizacion de la cotizacion'),
        ),
    ]
