# Generated by Django 3.2.8 on 2021-11-04 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0037_alter_cotizacion_mmtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 4, 0, 0), null=True, verbose_name='Fecha de realizacion de la cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='mmtos',
            field=models.ManyToManyField(blank=True, related_name='mantenimientosCotizacion', to='RPA.Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='periodisidadadicional',
            field=models.IntegerField(blank=True, null=True, verbose_name='Periodicidad adicional de actividad de mtto  a la regular'),
        ),
    ]
