# Generated by Django 3.2.8 on 2021-11-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0038_auto_20211104_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='dispositivos',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='periodoregular',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (6, '6')], null=True, verbose_name='Periodicidad regular de mmto al año'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='preguntaperiodoadicional',
            field=models.BooleanField(default=False, verbose_name='Quieres agregar periodicidad adicional a la regular?'),
        ),
    ]
