# Generated by Django 3.2 on 2021-11-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0033_rename_mantenimientos_cotizacion_mantenimientos'),
        ('RPA', '0038_alter_cotizacion_mantenimiento'),
    ]

    operations = [
    ]
