# Generated by Django 3.2.8 on 2021-11-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0039_auto_20211104_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='mmtos',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='periodoadicional',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (6, '6')], null=True, verbose_name='Periodicidad adicional a la regular'),
        ),
    ]
