# Generated by Django 3.2.8 on 2021-11-08 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0040_auto_20211104_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['encargadoTrabajo1']},
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='horasactividadadicional',
            field=models.IntegerField(blank=True, null=True, verbose_name='horas por actividad de mtto adicional =Importe de cantidad x Tiempo de ejecucion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 8, 0, 0), null=True, verbose_name='Fecha de realizacion de la cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='periodoadicional',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (4, '4'), (6, '6')], null=True, verbose_name='Periodicidad adicional a la regular'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cantidaddedispositivos',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad regular'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cantidaddispositivosextras',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad Extra'),
        ),
    ]
