# Generated by Django 3.2.8 on 2021-11-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0041_auto_20211108_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='horasactividad',
            field=models.FloatField(blank=True, null=True, verbose_name='horas por actividad de mtto regular =Importe de cantidad x Tiempo de ejecucion'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='horasactividadadicional',
            field=models.FloatField(blank=True, null=True, verbose_name='horas por actividad de mtto adicional =Importe de cantidad x Tiempo de ejecucion'),
        ),
    ]
