# Generated by Django 3.2.8 on 2021-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0042_auto_20211108_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='costototal',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo total = Costo regular + costo adicional'),
        ),
    ]
