# Generated by Django 3.2.8 on 2021-11-11 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0045_nombre_servicio_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dispositivo al que se le da mantenimiento'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 11, 0, 0), null=True, verbose_name='Fecha de realizacion de la cotizacion'),
        ),
    ]
