# Generated by Django 3.2.8 on 2021-11-17 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RPA', '0048_auto_20211117_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sufijo',
            new_name='InformacionPersonal',
        ),
    ]
