# Generated by Django 3.2.8 on 2021-11-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0049_rename_sufijo_informacionpersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionpersonal',
            name='apellido',
            field=models.CharField(blank=True, max_length=3, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='nombre',
            field=models.CharField(blank=True, max_length=3, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='sufijo',
            field=models.CharField(blank=True, max_length=3, verbose_name='Titulo Ej: Lic., Ing.'),
        ),
    ]
