# Generated by Django 3.2.8 on 2021-11-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0050_auto_20211117_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='sufijo',
            new_name='titulo',
        ),
    ]
