# Generated by Django 3.2.8 on 2021-11-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0051_rename_sufijo_informacionpersonal_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpersonal',
            name='apellido',
            field=models.CharField(blank=True, max_length=20, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombre'),
        ),
    ]
