# Generated by Django 3.2.8 on 2021-11-24 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0054_auto_20211119_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 24, 0, 0), null=True, verbose_name='Fecha de realizacion de la cotizacion'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='puesto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Puesto del usuario dentro de la empresa'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cantidaddedispositivos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad regular'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cantidaddispositivosextras',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad Extra'),
        ),
    ]
