# Generated by Django 3.2 on 2021-12-27 22:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0055_auto_20211124_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 27, 0, 0), null=True, verbose_name='Fecha de realizacion de la cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='periodoadicional',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (6, '6')], null=True, verbose_name='Periodicidad adicional a la regular'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='periodoregular',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (6, '6')], null=True, verbose_name='Periodicidad regular de mmto al año'),
        ),
        migrations.CreateModel(
            name='Nombre_servicio_CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo Mantenimiento')),
                ('tiempodeejecucion', models.FloatField(null=True, verbose_name='Tiempo de Ejecucion')),
                ('dispositivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dispositivo al que se le aplica el mantenimiento')),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.precio')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Nombre_servicio_CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo Mantenimiento')),
                ('tiempodeejecucion', models.FloatField(null=True, verbose_name='Tiempo de Ejecucion')),
                ('dispositivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dispositivo al que se le aplica el mantenimiento')),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.precio')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
