# Generated by Django 3.2.8 on 2022-08-15 22:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0055_auto_20211124_1322'),
    ]

    operations = [
        
    ]
