# Generated by Django 3.2 on 2021-12-28 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPA', '0056_auto_20211227_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento_CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodisidadactividades', models.IntegerField(blank=True, null=True, verbose_name='Periodicidad regular de actividad de mtto por año')),
                ('periodisidadadicional', models.IntegerField(blank=True, null=True, verbose_name='Periodicidad adicional de actividad de mtto  a la regular')),
                ('tiempoejecucion', models.FloatField(blank=True, null=True, verbose_name='Tiempo de ejecucion del mtto')),
                ('cantidaddedispositivos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad regular')),
                ('cantidaddispositivosextras', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad Extra')),
                ('horasactividad', models.FloatField(blank=True, null=True, verbose_name='horas por actividad de mtto regular =Importe de cantidad x Tiempo de ejecucion')),
                ('horasactividadadicional', models.FloatField(blank=True, null=True, verbose_name='horas por actividad de mtto adicional =Importe de cantidad x Tiempo de ejecucion')),
                ('costomantenimientoregular', models.FloatField(blank=True, null=True, verbose_name='Costo Regular = horas por actividad de mtto regular =Importe de cantidad x Tiempo de ejecucion')),
                ('costomantenimientoadicional', models.FloatField(blank=True, null=True, verbose_name='Costo Adicional = horas por actividad de mtto adicional =Importe de cantidad x Tiempo de ejecucion ')),
                ('costototal', models.FloatField(blank=True, null=True, verbose_name='Costo total = Costo regular + costo adicional')),
                ('dispositivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dispositivo al que se le da mantenimiento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.cotizacion')),
                ('encargadoTrabajo1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.precio', verbose_name='Encargado del trabajo')),
                ('titulonombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.nombre_servicio_cctv')),
            ],
            options={
                'ordering': ['encargadoTrabajo1', 'cantidaddedispositivos'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento_CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodisidadactividades', models.IntegerField(blank=True, null=True, verbose_name='Periodicidad regular de actividad de mtto por año')),
                ('periodisidadadicional', models.IntegerField(blank=True, null=True, verbose_name='Periodicidad adicional de actividad de mtto  a la regular')),
                ('tiempoejecucion', models.FloatField(blank=True, null=True, verbose_name='Tiempo de ejecucion del mtto')),
                ('cantidaddedispositivos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad regular')),
                ('cantidaddispositivosextras', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de dispositivos a considerar en periodicidad Extra')),
                ('horasactividad', models.FloatField(blank=True, null=True, verbose_name='horas por actividad de mtto regular =Importe de cantidad x Tiempo de ejecucion')),
                ('horasactividadadicional', models.FloatField(blank=True, null=True, verbose_name='horas por actividad de mtto adicional =Importe de cantidad x Tiempo de ejecucion')),
                ('costomantenimientoregular', models.FloatField(blank=True, null=True, verbose_name='Costo Regular = horas por actividad de mtto regular =Importe de cantidad x Tiempo de ejecucion')),
                ('costomantenimientoadicional', models.FloatField(blank=True, null=True, verbose_name='Costo Adicional = horas por actividad de mtto adicional =Importe de cantidad x Tiempo de ejecucion ')),
                ('costototal', models.FloatField(blank=True, null=True, verbose_name='Costo total = Costo regular + costo adicional')),
                ('dispositivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dispositivo al que se le da mantenimiento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.cotizacion')),
                ('encargadoTrabajo1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.precio', verbose_name='Encargado del trabajo')),
                ('titulonombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RPA.nombre_servicio_ca')),
            ],
            options={
                'ordering': ['encargadoTrabajo1', 'cantidaddedispositivos'],
            },
        ),
    ]
